# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b156dbd74d6b1140ee88e950d956c1373558c694c2b4bf49b7246e8012330a99cd83f7ce888c15a3b9c0608822d06680c71d30119d08b76dc331c45333eec8e6

test:
  secret_key_base: 208338bd5eecb980ac4a6fee0ff3848c3374851215329cffc055087147be558ff7fd0a0b69f59059d5c2caba43852d4345d27b700c5c169230620072db1d63ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
